matrix:
  include:
    - name: Server
      language: rust
      rust: 1.29.0
      cache: cargo
      install:
        - cargo build -p server --verbose
      script:
        - cargo build -p server --verbose
        - cargo test -p server --verbose

    - name: Primitive game
      language: rust
      rust: 1.29.0
      cache: cargo
      install:
        - rustup target add wasm32-unknown-unknown
        - cargo build -p primitive-game --verbose --target=wasm32-unknown-unknown
      script:
        - cargo build -p primitive-game --verbose --target=wasm32-unknown-unknown
        - cargo test -p primitive-game --verbose

    - name: Primitive game builder
      language: rust
      rust: 1.29.0
      cache: cargo
      install:
        - cargo build -p primitive-game-builder --verbose
      script:
        - cargo build -p primitive-game-builder --verbose

    - name: Client
      language: node_js
      node_js: 8
      cache:
        directories:
          - $HOME/.npm
      env:
        - NODE_ENV=development
      before_install:
        - cd client
      script:
        - npm run lint
        - npm run build

notifications:
  email: false
