[package]
name = "server"
version = "0.1.0"
authors = [
    "Vytautas Strimaitis <vstrimaitis@gmail.com>",
    "Domantas Jadenkus <djadenkus@gmail.com"
]

[dependencies]
ws = "0.7.6"
log = "0.4.2"
env_logger = "0.5.10"
